const Q=window.PULSE_QUESTIONS||[];
const SUPABASE_URL='https://ngveomdzvlzuawsvouck.supabase.co';
const SUPABASE_KEY='sb_publishable_ELEGNyhypq8b-dY9QPClCA_8VLCkV9k';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const STORE='pulseRhumatoV3';
const fresh=()=>({current:0,answers:{},reviews:{},xp:0,streak:0,lastActivity:null,updatedAt:new Date(0).toISOString()});
let state=loadLocal(),view='home',reviewFilter='today',user=null,syncState='local',cloudTimer=null,authMessage='';
function loadLocal(){try{return {...fresh(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return fresh()}}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function today(){let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function addDays(n){let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function touchActivity(){const t=today();if(state.lastActivity!==t){if(state.lastActivity){let y=new Date();y.setDate(y.getDate()-1);let yd=y.getFullYear()+'-'+String(y.getMonth()+1).padStart(2,'0')+'-'+String(y.getDate()).padStart(2,'0');state.streak=state.lastActivity===yd?(state.streak||0)+1:1}else state.streak=1;state.lastActivity=t}}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));if(user){syncState='syncing';clearTimeout(cloudTimer);cloudTimer=setTimeout(saveCloud,450)}}
async function saveCloud(){if(!user)return;const {error}=await sb.from('app_state').upsert({user_id:user.id,state},{onConflict:'user_id'});syncState=error?'error':'cloud';render()}
async function loadCloud(){if(!user)return;syncState='syncing';render();const {data,error}=await sb.from('app_state').select('state,updated_at').eq('user_id',user.id).maybeSingle();if(error){syncState='error';render();return}if(data?.state){const cloud={...fresh(),...data.state};if(new Date(cloud.updatedAt||data.updated_at)>new Date(state.updatedAt||0)){state=cloud;localStorage.setItem(STORE,JSON.stringify(state))}else await saveCloud()}else await saveCloud();syncState='cloud';render()}
function answeredCount(){return Object.values(state.answers).filter(a=>a.validated).length}
function coveredCourses(){return new Set(Q.filter(q=>state.answers[q.id]?.validated).map(q=>q.course)).size}
function dueItems(filter=reviewFilter){const t=today();return Q.filter(q=>{const r=state.reviews[q.id];if(!r)return false;if(filter==='excluded')return r.status==='excluded';if(r.status==='excluded')return false;if(filter==='all')return true;if(filter==='today')return r.due===t;if(filter==='late')return r.due<t;if(filter==='upcoming')return r.due>t;return false})}
function dueToday(){return dueItems('today').length+dueItems('late').length}
function syncLabel(){if(syncState==='cloud')return '<span class="dot on"></span>Cloud synchronisé';if(syncState==='syncing')return '<span class="dot"></span>Synchronisation…';if(syncState==='error')return '<span class="dot" style="background:var(--red)"></span>Erreur cloud';return '<span class="dot"></span>Sauvegarde locale'}
function shell(content){const nav=[['home','⌂','Accueil'],['train','✦','Entraînement'],['reviews','↻','Répétition espacée'],['stats','◫','Statistiques'],['account','◎','Compte']];return `<div class="app"><aside class="sidebar"><div class="logo"><span class="pulsemark">P</span><div>Pulse Rhumato<small>MAÎTRISE • STAGE • ÉCHO</small></div></div><div class="nav">${nav.map(n=>`<button data-view="${n[0]}" class="${view===n[0]?'active':''}"><span>${n[1]}</span>${n[2]}${n[0]==='reviews'?`<span class="count">${dueToday()}</span>`:''}</button>`).join('')}</div><div class="sidefoot"><div class="syncbox">${syncLabel()}<br><span>${user?esc(user.email):'Non connecté'}</span></div></div></aside><main class="main"><div class="topbar"><div><div class="eyebrow">Pulse learning system</div><h1>${view==='train'?'Entraînement clinique':view==='reviews'?'Répétition espacée':view==='stats'?'Performance':view==='account'?'Compte & synchronisation':'Cockpit Rhumato'}</h1></div><div class="topactions"><span class="pill">🔥 ${state.streak||0} j</span><span class="pill">⚡ ${state.xp||0} XP</span><button class="btn ${user?'ghost':'primary'}" data-view="account">${user?'☁ Synchronisé':'Se connecter'}</button></div></div>${content}</main><nav class="mobilebar">${nav.slice(0,4).map(n=>`<button data-view="${n[0]}" class="${view===n[0]?'active':''}">${n[1]}<br>${n[2].split(' ')[0]}</button>`).join('')}</nav></div>`}
function home(){const n=answeredCount(),pct=Math.min(100,Math.round(n/727*100)),daily=Object.values(state.answers).filter(a=>a.validated&&a.date===today()).length;return shell(`<section class="grid4 fade"><div class="card metric"><span class="label">Questions uniques</span><strong>${n}<small>/727+</small></strong><div class="micro">${pct}% du programme cible</div></div><div class="card metric"><span class="label">Cours couverts</span><strong>${coveredCourses()}<small>/107</small></strong><div class="micro">Priorité stage</div></div><div class="card metric"><span class="label">À revoir</span><strong>${dueToday()}</strong><div class="micro">Aujourd’hui + retard</div></div><div class="card metric"><span class="label">Maîtrise</span><strong>${n?Math.round(Object.values(state.answers).filter(a=>a.validated&&a.correct).length/n*100):0}%</strong><div class="micro">Sur les réponses validées</div></div></section><section class="hero fade"><div class="card mission"><div class="eyebrow">Mission du jour</div><h2>Construis des automatismes de rhumatologue.</h2><p>Cas denses, décisions prioritaires, échographie et réactivation active. Chaque réponse est enregistrée par question et synchronisée dans ton compte.</p><div class="progress"><div style="width:${Math.min(100,daily/10*100)}%"></div></div><button class="btn primary" data-view="train">Continuer • Q${Math.min(state.current+1,Q.length)}/${Q.length}</button></div><div class="card today"><div class="eyebrow">Objectif quotidien</div><div class="ring" style="--pct:${Math.min(100,daily/10*100)}%"><b>${daily}/10</b></div><h3 style="text-align:center">Questions aujourd’hui</h3><button class="btn ghost" style="width:100%" data-view="reviews">${dueToday()} révision(s) à traiter</button></div></section>`)}
function train(){if(!Q.length)return shell('<div class="card empty">Aucune question disponible.</div>');state.current=Math.max(0,Math.min(state.current,Q.length-1));const q=Q[state.current],a=state.answers[q.id]||{},r=state.reviews[q.id];return shell(`<section class="train fade"><div class="card question"><div class="qhead"><div class="tags"><span class="tag p1">${esc(q.priority)}</span><span class="tag ${q.module.includes('Écho')?'echo':''}">${esc(q.module)}</span></div><span class="counter">Question ${state.current+1} / ${Q.length}</span></div><div class="stem">${esc(q.stem)}</div><div class="options">${q.options.map((o,i)=>{let c=a.selected===i?' selected':'';if(a.validated&&i===q.answer)c+=' correct';else if(a.validated&&a.selected===i&&i!==q.answer)c+=' wrong';return `<button class="option${c}" data-opt="${i}" ${a.validated?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`}).join('')}</div><div class="actions"><button class="btn ghost" id="hard">${a.hard?'★ Difficile':'☆ Marquer difficile'}</button>${!a.validated?`<button class="btn primary" id="validate" ${a.selected===undefined?'disabled':''}>Valider la réponse</button>`:`<button class="btn primary" id="next">Question suivante →</button>`}</div>${a.validated?`<div class="feedback ${a.correct?'':'bad'}"><b>${a.correct?'✓ Bonne réponse':'Correction'}</b><br>${esc(q.correction)}</div><div class="reviewpicker"><b>Quand revoir cette question ?</b><div class="choices">${[['J1',1],['J2',2],['J7',7],['J10',10],['Ne pas revoir',null]].map(x=>`<button class="choice ${(r?.stage===x[0]||(x[1]===null&&r?.status==='excluded'))?'active':''}" data-review="${x[0]}">${x[0]}</button>`).join('')}</div></div>`:''}</div><aside class="card coursecard"><div class="eyebrow">Cours source</div><h2>${esc(q.course)}</h2><div class="tags"><span class="tag">${esc(q.module)}</span><span class="tag p1">${esc(q.priority)}</span></div><p>${esc(q.courseText)}</p><a class="source" href="${q.source}" target="_blank" rel="noopener">Ouvrir le cours Notion ↗</a><details class="german"><summary>🇩🇪 Deutsch • Fachsprache</summary><p>${esc(q.german)}</p></details></aside></section>`)}
function reviews(){const items=dueItems();return shell(`<div class="toolbar fade">${[['today','À revoir aujourd’hui'],['late','En retard'],['upcoming','À venir'],['all','Toutes'],['excluded','Ne pas revoir']].map(x=>`<button data-filter="${x[0]}" class="${reviewFilter===x[0]?'active':''}">${x[1]} <b>${dueItems(x[0]).length}</b></button>`).join('')}</div><div class="list fade">${items.length?items.map(q=>{const r=state.reviews[q.id];return `<div class="reviewrow"><div><b>${esc(q.course)}</b><small>${r.status==='excluded'?'Exclue des révisions':`${r.stage} • ${r.due}`}</small></div><button data-jump="${q.id}">${r.status==='excluded'?'Réactiver':'Réviser'}</button></div>`}).join(''):'<div class="card empty">Rien dans cette file. Tu es à jour.</div>'}</div>`)}
function stats(){const n=answeredCount(),good=Object.values(state.answers).filter(a=>a.validated&&a.correct).length,hard=Object.values(state.answers).filter(a=>a.hard).length;return shell(`<section class="grid4 fade"><div class="card metric"><span class="label">Réussite</span><strong>${n?Math.round(good/n*100):0}%</strong><div class="micro">${good}/${n} correctes</div></div><div class="card metric"><span class="label">Points difficiles</span><strong>${hard}</strong><div class="micro">À renforcer</div></div><div class="card metric"><span class="label">Série</span><strong>${state.streak||0} j</strong><div class="micro">Régularité</div></div><div class="card metric"><span class="label">XP</span><strong>${state.xp||0}</strong><div class="micro">Maîtrise cumulée</div></div></section><section class="card mission fade" style="margin-top:14px;min-height:180px"><div class="eyebrow">Cap 2 novembre</div><h2>${n}/727+ questions uniques</h2><p>Les réactivations J1/J2/J7/J10 ne gonflent pas le compteur de questions uniques. Elles renforcent la mémorisation sans fausser ta couverture du programme.</p><div class="progress"><div style="width:${Math.min(100,n/727*100)}%"></div></div></section>`)}
function account(){if(user)return shell(`<div class="authwrap fade"><div class="card authcard"><div class="eyebrow">Compte Pulse</div><h2>Progression dans le cloud.</h2><p>Connecté avec <b>${esc(user.email)}</b>. Ta progression, la question courante et tes échéances de répétition sont sauvegardées dans Supabase et récupérables sur Safari, iPhone ou Mac.</p><div class="notice">${syncLabel()} • dernière modification ${new Date(state.updatedAt).toLocaleString('fr-FR')}</div><div class="authbuttons"><button class="btn primary" id="syncnow">Synchroniser maintenant</button><button class="btn ghost" id="logout">Se déconnecter</button></div></div></div>`);return shell(`<div class="authwrap fade"><div class="card authcard"><div class="eyebrow">Pulse Cloud</div><h2>Retrouve ta progression partout.</h2><p>Crée un compte avec ton e-mail et un mot de passe, ou reconnecte-toi. La clé publique Supabase est utilisée côté navigateur ; tes données sont protégées par RLS et accessibles uniquement à ton utilisateur.</p><div class="field"><label>E-mail</label><input id="email" type="email" autocomplete="email" placeholder="ton@email.fr"></div><div class="field"><label>Mot de passe</label><input id="password" type="password" autocomplete="current-password" minlength="8" placeholder="8 caractères minimum"></div><div class="authbuttons"><button class="btn primary" id="login">Se connecter</button><button class="btn ghost" id="signup">Créer mon compte</button></div>${authMessage?`<div class="notice">${esc(authMessage)}</div>`:''}<div class="notice">À la première inscription, Supabase peut demander une confirmation par e-mail. Clique le lien reçu, puis reviens ici et connecte-toi.</div></div></div>`)}
function render(){let content=view==='train'?train():view==='reviews'?reviews():view==='stats'?stats():view==='account'?account():home();document.getElementById('root').innerHTML=content;bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{const q=Q[state.current],a=state.answers[q.id]||{};if(a.validated)return;state.answers[q.id]={...a,selected:+b.dataset.opt};save();render()});let v=document.getElementById('validate');if(v)v.onclick=()=>{const q=Q[state.current],a=state.answers[q.id]||{};if(a.selected===undefined)return;const first=!a.validated;touchActivity();state.answers[q.id]={...a,validated:true,correct:a.selected===q.answer,date:a.date||today()};if(first)state.xp=(state.xp||0)+(a.selected===q.answer?20:10);save();render()};let h=document.getElementById('hard');if(h)h.onclick=()=>{const q=Q[state.current],a=state.answers[q.id]||{};state.answers[q.id]={...a,hard:!a.hard};save();render()};let n=document.getElementById('next');if(n)n.onclick=()=>{state.current=(state.current+1)%Q.length;save();render()};document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const q=Q[state.current],stage=b.dataset.review;if(stage==='Ne pas revoir')state.reviews[q.id]={stage:null,due:null,status:'excluded'};else{const days={J1:1,J2:2,J7:7,J10:10}[stage];state.reviews[q.id]={stage,due:addDays(days),status:'scheduled'}}save();render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{reviewFilter=b.dataset.filter;render()});document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{let i=Q.findIndex(q=>q.id===b.dataset.jump);if(i>=0){if(state.reviews[Q[i].id]?.status==='excluded')state.reviews[Q[i].id]={stage:'J2',due:addDays(2),status:'scheduled'};state.current=i;view='train';save();render()}});let li=document.getElementById('login');if(li)li.onclick=login;let su=document.getElementById('signup');if(su)su.onclick=signup;let lo=document.getElementById('logout');if(lo)lo.onclick=async()=>{await sb.auth.signOut();user=null;syncState='local';view='home';render()};let sn=document.getElementById('syncnow');if(sn)sn.onclick=saveCloud}
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||!password){authMessage='Renseigne ton e-mail et ton mot de passe.';render();return}authMessage='Connexion…';render();const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){authMessage=error.message;render();return}user=data.user;authMessage='';await loadCloud();view='home';render()}
async function signup(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||password.length<8){authMessage='Utilise un e-mail valide et un mot de passe d’au moins 8 caractères.';render();return}authMessage='Création du compte…';render();const {data,error}=await sb.auth.signUp({email,password});if(error){authMessage=error.message;render();return}if(data.session){user=data.user;authMessage='';await loadCloud();view='home'}else authMessage='Compte créé. Vérifie ton e-mail de confirmation, puis reviens te connecter.';render()}
async function init(){render();const {data}=await sb.auth.getUser();if(data?.user){user=data.user;await loadCloud()}sb.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session?.user&&!user){user=session.user;await loadCloud()}if(event==='SIGNED_OUT'){user=null;syncState='local';render()}});render()}
init();