(()=>{
const bank=window.PULSE_QUESTIONS||[],courses=window.PULSE_COURSES||[],docs=window.PULSE_UNESS_ALL||[],map=window.PULSE_SOURCE_MAP_V16||{};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/œ/g,'oe').replace(/[^a-z0-9%+./-]+/g,' ').replace(/\s+/g,' ').trim();
const clean=s=>String(s||'').replace(/\u0007|\f/g,' ').replace(/[•▪►➢]/g,' ').replace(/І\s*\d+/g,' ').replace(/\s+/g,' ').trim();
const legal=/droit d'auteur|propriété intellectuelle|interdit à la vente|mise à disposition du public|réservées? au collège|advisory boards?|liens? d.intérêts|aides? pour des recherches|cours, formations|photographiques|iconographiques|recherches cliniques|copyright|www\.|https?:|doi\b|et al\.|bibliograph|référence/i;
const hi=/\b(doit|doivent|recommand|indiqu|contre-indiqu|urgence|priorit|diagnostic|traitement|surveillance|risque|complication|pronostic|prévenir|dépist|objectif|critère|seuil|dose|posologie|sensibilit|spécificit|ponction|infiltration|échograph|doppler|prf|gain|anisotrop|artefact|sonde|balayage|cortico|méthotrex|biomédicament|anti-tnf|rituximab|infection|vaccin|anticoagul|cristaux|synovite|ténosynovite)\b/i;
const critical=/\b(urgence|contre-indiqu|indispensable|toujours|jamais|première intention|1ère intention|gold standard|recommand|doit|seuil|dose|posologie|risque|complication|mortalité|pronostic|sensibilit|spécificit|anisotrop|prf|doppler|gain)\b/i;
const stop=new Set('avec dans pour sans sous chez entre après avant cette cette les des une un est sont être avoir plus moins leur leurs dont lors peut peuvent doit doivent cours support patient patients maladie traitement diagnostic prise charge'.split(' '));
function words(s){return norm(s).split(' ').filter(w=>w.length>3&&!stop.has(w)&&!/^[0-9.]+$/.test(w))}
function exactText(c){const f=map[c.id];if(!f)return'';const nf=norm(f);return docs.filter(d=>norm(d.f||d.file)===nf).map(d=>d.x||'').join('\n')}
function oldFacts(c){try{return (window.PULSE_V12_FACTS_FOR?.(c.title)?.facts||[]).map(clean)}catch{return[]}}
function sentences(text){const raw=String(text||'').replace(/\r/g,'\n').replace(/І\s*\d+/g,'\n').replace(/[•▪►➢]/g,'\n');const pieces=[];for(const line of raw.split(/\n+/)){const l=clean(line);if(!l||legal.test(l))continue;const chunks=l.split(/(?<=[.!?;:])\s+(?=[A-ZÀ-ÖØ-Þ0-9])/);for(let x of chunks){x=clean(x).replace(/^[-–—:;,]+\s*/,'');if(x.length>=42&&x.length<=300&&x.split(/\s+/).length>=7&&!legal.test(x)&&!/^([A-ZÀ-ÖØ-Þ0-9 ]{8,})$/.test(x))pieces.push(x)}}return pieces}
function scoreFact(s,c,fromFacts=false){let n=fromFacts?5:0;if(hi.test(s))n+=5;if(critical.test(s))n+=5;if(/\d/.test(s))n+=2;if(/%|mg|kg|ml|mm|cm|hz|semaines?|mois|jours?|ans?|sa\b/i.test(s))n+=2;const tw=words(c.title);const ns=norm(s);n+=Math.min(5,tw.filter(w=>ns.includes(w)).length);if(s.length>=65&&s.length<=210)n+=2;if(/[()]/.test(s))n+=1;return n}
function candidates(c){const arr=[...oldFacts(c).map(s=>({s,boost:true})),...sentences(exactText(c)).map(s=>({s,boost:false}))];const out=[];for(const o of arr){const s=clean(o.s);if(s.length<38||legal.test(s))continue;const key=norm(s).replace(/\d+/g,'#').slice(0,150);if(out.some(x=>x.key===key||norm(x.s).slice(0,105)===norm(s).slice(0,105)))continue;out.push({s,key,score:scoreFact(s,c,o.boost)})}return out.sort((a,b)=>b.score-a.score||a.s.length-b.s.length)}
function category(s){const n=norm(s);if(/echo|doppler|prf|gain|anisotrop|sonde|balayage|artefact/.test(n))return'échographie';if(/trait|dose|mg|cortico|methotrex|biomed|anti tnf|ritux|ains|infiltr|chirurg|reeducation/.test(n))return'traitement';if(/diagn|clinique|biolog|imager|irm|radio|critere|anticorps|ponction|signe|symptom/.test(n))return'diagnostic';if(/surveill|risque|contre indiqu|complication|tolerance|suivi|urgence|pronostic/.test(n))return'surveillance';return'connaissance'}
function anchors(list,n=4){const out=[],seen=new Set();for(const x of list){const cat=category(x.s);if(!seen.has(cat)||out.length>=3){out.push(x);seen.add(cat)}if(out.length>=n)break}return out}
function swapNumber(s){const m=s.match(/\b(\d+(?:[,.]\d+)?)\s*(%|mg|kg|ml|mm|cm|Hz|hz|jours?|semaines?|mois|ans?|SA)?\b/);if(!m)return null;const v=parseFloat(m[1].replace(',','.'));if(!Number.isFinite(v))return null;let nv=v===0?1:v<2?v*2:v<10?v+3:v<100?Math.round(v*1.5):Math.round(v*.6);if(nv===v)nv=v+1;return s.slice(0,m.index)+String(nv).replace('.',',')+(m[2]?' '+m[2]:'')+s.slice(m.index+m[0].length)}
function invert(s){const rules=[[/\bdoit être\b/i,'ne doit pas être'],[/\bdoivent être\b/i,'ne doivent pas être'],[/\bdoit\b/i,'ne doit pas'],[/\brecommandé(e|es|s)?\b/i,'déconseillé$1'],[/\bindiqué(e|es|s)?\b/i,'contre-indiqué$1'],[/\baugmente\b/i,'diminue'],[/\bdiminue\b/i,'augmente'],[/\bsupérieur(e)?\b/i,'inférieur$1'],[/\binférieur(e)?\b/i,'supérieur$1'],[/\bavant\b/i,'après'],[/\baprès\b/i,'avant'],[/\bprécoce\b/i,'tardif'],[/\bpositif\b/i,'négatif'],[/\bnégatif\b/i,'positif']];for(const [r,v] of rules)if(r.test(s))return s.replace(r,v);return null}
function absolutize(s){if(/\b(peut|peuvent|parfois|éventuellement|selon|en cas de)\b/i.test(s))return s.replace(/\bpeut\b/i,'doit toujours').replace(/\bpeuvent\b/i,'doivent toujours').replace(/\bparfois\b/i,'dans tous les cas').replace(/\béventuellement\b/i,'systématiquement').replace(/\bselon\b/i,'indépendamment de');return 'Il est recommandé de considérer systématiquement l’inverse de cette proposition, quel que soit le contexte clinique.'}
function distractors(s){const a=[invert(s),swapNumber(s),absolutize(s)].filter(Boolean).map(clean);const uniq=[];for(const x of a){if(norm(x)!==norm(s)&&!uniq.some(y=>norm(y)===norm(x)))uniq.push(x)}while(uniq.length<3)uniq.push(['Cette proposition doit être appliquée systématiquement sans tenir compte du contexte clinique.','Le support recommande de ne pas tenir compte des contre-indications ni de la surveillance.','Cette conduite est présentée comme obligatoire chez tous les patients sans exception.'][uniq.length]);return uniq.slice(0,3)}
function rotate(correct,wrong,seed){const opts=[correct,...wrong],shift=seed%4;return opts.slice(shift).concat(opts.slice(0,shift))}
function stemFor(s,c,i,anchor){const cat=category(s);if(anchor)return`ANCRAGE +++ — Parmi ces propositions, laquelle correspond au message prioritaire du cours « ${c.title} » ?`;if(cat==='traitement')return`Concernant la stratégie thérapeutique enseignée dans « ${c.title} », quelle proposition est exacte ?`;if(cat==='diagnostic')return`Concernant le diagnostic ou le bilan dans « ${c.title} », quelle proposition est exacte ?`;if(cat==='surveillance')return`Concernant la surveillance, les risques ou les pièges de « ${c.title} », quelle proposition est exacte ?`;if(cat==='échographie')return`Concernant la technique ou la sémiologie échographique de « ${c.title} », quelle proposition est exacte ?`;return`D’après le support « ${c.title} », quelle proposition est exacte ?`}
let added=0,anchorCount=0;const perCourse={};
for(const c of courses){const cand=candidates(c);if(!cand.length)continue;const target=Math.min(30,Math.max(12,Math.round(cand.length*.72))),anc=anchors(cand,Math.min(4,Math.max(2,Math.ceil(target/8))));const anchorKeys=new Set(anc.map(x=>x.key));const chosen=[...anc,...cand.filter(x=>!anchorKeys.has(x.key))].slice(0,target);let ci=0;for(const x of chosen){ci++;const isAnchor=anchorKeys.has(x.key),id=`v25-${isAnchor?'anchor':'deep'}-${c.id}-${ci}`;if(bank.some(q=>q.id===id))continue;const wrong=distractors(x.s),opts=rotate(x.s,wrong,ci+c.id.charCodeAt(c.id.length-1)),answer=opts.findIndex(o=>o===x.s);bank.push({id,course:c.title,module:c.module,priority:isAnchor?'SOCLE +++':(x.score>=10?'P1 Stage':'P2'),anchor:isAnchor,sourceLabel:`PDF UNESS • ${isAnchor?'ANCRAGE +++':'couverture approfondie'} • ${map[c.id]||'support source'}`,stem:stemFor(x.s,c,ci,isAnchor),options:opts,answer,correction:`${isAnchor?'Point d’ancrage prioritaire':'Point du support'} : ${x.s}`,sourceFact:x.s,sourceFile:map[c.id]||null,coverageCategory:category(x.s)});added++;if(isAnchor)anchorCount++}perCourse[c.id]=ci}
window.PULSE_QUESTIONS=bank;window.PULSE_QCM_V25={added,anchorCount,perCourse,total:bank.length};
})();