(()=>{
const h=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const foundCache=new Map(),docCache=new Map();
function addFullscreen(root=document){root.querySelectorAll('.v17viewer').forEach(v=>{const tb=v.querySelector('.v17toolbar');if(!tb||tb.querySelector('.v18full'))return;const b=document.createElement('button');b.className='v18full';b.type='button';b.textContent='⛶ Plein écran';b.onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else v.requestFullscreen?.()};tb.appendChild(b)})}
function stopViewer(host){try{host._pulseRenderTask?.cancel?.()}catch{}host._pulseRenderTask=null}
async function cachedPdf(title){
 const api=window.PULSE_PDF_READER,pdfjs=window.pdfjsLib;if(!api?.pdfFor)throw new Error('lecteur indisponible');if(!pdfjs)throw new Error('PDF.js indisponible');
 pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
 let found=foundCache.get(title);if(!found){found=await api.pdfFor(title,'qcmside');if(!found)throw new Error('PDF non disponible');foundCache.set(title,found)}
 let promise=docCache.get(title);if(!promise){promise=pdfjs.getDocument({url:found.url}).promise.catch(e=>{docCache.delete(title);foundCache.delete(title);throw e});docCache.set(title,promise)}
 return{found,pdf:await promise}
}
async function miniViewer(host,title){
 if(!host||host.dataset.ready==='1'&&host.dataset.title===title)return;
 stopViewer(host);const generation=String((+host.dataset.generation||0)+1);host.dataset.generation=generation;host.dataset.ready='1';host.dataset.title=title;
 host.innerHTML=`<section class="v15pdf v17pdf"><div class="v15pdfHead"><div><span>COURS À CÔTÉ DU QCM</span><b>${h(title)}</b></div><span class="v15pdfState">${docCache.has(title)?'Ouverture instantanée…':'Chargement…'}</span></div><div class="v15pdfBody"><div class="v15pdfEmpty"><div class="v15docIcon">PDF</div><b>${docCache.has(title)?'Réouverture du support…':'Ouverture du support…'}</b></div></div></section>`;
 try{
  const {found,pdf}=await cachedPdf(title);if(host.dataset.generation!==generation)return;
  const body=host.querySelector('.v15pdfBody'),stateEl=host.querySelector('.v15pdfState');if(!body||!stateEl)return;stateEl.textContent=found.cloud?'☁ PDF prêt':'PDF local prêt';stateEl.classList.add('ready');
  body.innerHTML=`<div class="v17viewer"><div class="v17toolbar"><button data-pdf-prev>←</button><span>Page <b data-pdf-page>1</b> / <b data-pdf-total>${pdf.numPages}</b></span><button data-pdf-next>→</button><span class="v17sep"></span><button data-pdf-minus>−</button><span data-pdf-zoom>100%</span><button data-pdf-plus>+</button><a href="${h(found.url)}" target="_blank" rel="noopener">Ouvrir ↗</a></div><div class="v17stage"><canvas></canvas><div class="v17loading">Affichage…</div></div><div class="v15pdfTools"><span>${h(found.file)}</span></div></div>`;
  let page=1,zoom=1,renderSeq=0;const canvas=body.querySelector('canvas'),ctx=canvas?.getContext('2d'),stage=body.querySelector('.v17stage'),loading=body.querySelector('.v17loading');if(!canvas||!ctx||!stage)return;
  async function draw(){const seq=++renderSeq;try{host._pulseRenderTask?.cancel?.()}catch{}if(host.dataset.generation!==generation)return;loading.style.display='grid';try{const p=await pdf.getPage(page);if(seq!==renderSeq||host.dataset.generation!==generation)return;const base=p.getViewport({scale:1}),fit=Math.max(.35,Math.min(2,(stage.clientWidth-24)/base.width)),vp=p.getViewport({scale:fit*zoom}),ratio=window.devicePixelRatio||1;canvas.width=Math.floor(vp.width*ratio);canvas.height=Math.floor(vp.height*ratio);canvas.style.width=vp.width+'px';canvas.style.height=vp.height+'px';ctx.setTransform(ratio,0,0,ratio,0,0);const task=p.render({canvasContext:ctx,viewport:vp});host._pulseRenderTask=task;await task.promise;if(seq!==renderSeq||host.dataset.generation!==generation)return;body.querySelector('[data-pdf-page]').textContent=page;body.querySelector('[data-pdf-zoom]').textContent=Math.round(zoom*100)+'%'}catch(e){if(e?.name!=='RenderingCancelledException')throw e}finally{if(seq===renderSeq&&host.dataset.generation===generation)loading.style.display='none'}}
  body.querySelector('[data-pdf-prev]').onclick=()=>{if(page>1){page--;draw()}};body.querySelector('[data-pdf-next]').onclick=()=>{if(page<pdf.numPages){page++;draw()}};body.querySelector('[data-pdf-minus]').onclick=()=>{zoom=Math.max(.6,zoom-.1);draw()};body.querySelector('[data-pdf-plus]').onclick=()=>{zoom=Math.min(2.2,zoom+.1);draw()};await draw();if(host.dataset.generation===generation)addFullscreen(host)
 }catch(e){if(e?.name==='RenderingCancelledException'||host.dataset.generation!==generation)return;host.dataset.ready='';host.innerHTML=`<section class="v15pdf"><div class="v15pdfEmpty"><div class="v15docIcon">PDF</div><b>Cours non disponible dans ce navigateur.</b><p>${h(e.message)}</p></div></section>`}
}
function enhanceSeries(){const q=document.querySelector('.rpPlanQuestion');if(!q)return;const title=document.querySelector('.seriesBar b')?.textContent?.replace(/^Plan\s*•\s*/i,'').trim();if(!title)return;let grid=q.closest('.v18StudyGrid');if(!grid){grid=document.createElement('div');grid.className='v18StudyGrid fade';q.parentNode.insertBefore(grid,q);const side=document.createElement('div');side.className='v18StudyPdf';side.dataset.title=title;grid.appendChild(side);grid.appendChild(q);miniViewer(side,title)}else{const side=grid.querySelector('.v18StudyPdf');if(side&&side.dataset.title!==title)miniViewer(side,title)}const corr=document.querySelector('.v15correction');if(corr&&corr.parentNode!==grid)grid.appendChild(corr)}
function enhanceCourse(){addFullscreen();const viewer=document.querySelector('.courseDetail .v17viewer');if(viewer){const stage=viewer.querySelector('.v17stage');if(stage&&!stage.dataset.v18resize){stage.dataset.v18resize='1';new ResizeObserver(()=>{const z=viewer.querySelector('[data-pdf-zoom]');if(z)z.title='Ajustement automatique à la largeur'}).observe(stage)}}}
let t;function tick(){clearTimeout(t);t=setTimeout(()=>{enhanceCourse();enhanceSeries()},45)}new MutationObserver(tick).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('resize',tick);setTimeout(tick,160);
window.PULSE_PLAN_PDF_CACHE={clear:()=>{foundCache.clear();docCache.clear()},size:()=>docCache.size};
})();