(()=>{
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/œ/g,'oe').replace(/[^a-z0-9]+/g,' ').trim();
const h=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function courseForTitle(title){return (window.PULSE_COURSES||[]).find(c=>c.title===title)||null}
function metaFor(title){const c=courseForTitle(title),expected=c&&window.PULSE_SOURCE_MAP_V16?.[c.id];if(expected){const d=(window.PULSE_UNESS_ALL||[]).find(x=>norm(x.f||'')===norm(expected));if(d)return d}return null}
function cleanLine(x=''){return String(x).replace(/[•▪►➢]/g,' ').replace(/\s+/g,' ').replace(/^[-–—:;,]+\s*/,'').trim()}
function sentence(x=''){let s=cleanLine(x).replace(/^\d+[.)-]?\s*/,'');if(!s)return'';s=s.charAt(0).toUpperCase()+s.slice(1);if(!/[.!?]$/.test(s))s+='.';return s}
function usable(s){return s.length>=34&&s.length<=260&&!/mentions légales|liens d.intérêts|copyright|propriété intellectuelle|bibliographie|références|https?:|www\.|@|doi:/i.test(s)}
function isHeading(s){if(!s||s.length<3||s.length>92)return false;if(/^(sommaire|plan|objectifs?|introduction|conclusion|diagnostic|traitement|surveillance|clinique|biologie|imagerie|épidémiologie|physiopathologie|définition|prise en charge|indications?|contre-indications?|complications?|technique|matériel|installation|résultats?|classification|critères?|pronostic|suivi|sémiologie|anatomie|réglages?|articulation|tendon|muscle|nerf|bourse)/i.test(s))return true;if(/^\d+(?:[.)]|\s+-|\s+[A-ZÀ-ÖØ-Þ])/.test(s))return true;const letters=s.replace(/[^A-Za-zÀ-ÖØ-öø-ÿ]/g,'');const upp=(letters.match(/[A-ZÀ-ÖØ-Þ]/g)||[]).length;return letters.length>5&&upp/letters.length>.72}
function outline(title){const meta=metaFor(title),course=courseForTitle(title),text=String(meta?.x||'').replace(/\f/g,'\n').replace(/\r/g,'');const lines=text.split(/\n+/).map(cleanLine).filter(Boolean);const out=[];for(let i=0;i<lines.length&&out.length<12;i++){const hd=lines[i];if(!isHeading(hd))continue;if(/^(sommaire|plan|objectifs?)$/i.test(hd))continue;let key='';for(let j=i+1;j<Math.min(lines.length,i+7);j++){if(isHeading(lines[j]))break;const s=sentence(lines[j]);if(usable(s)){key=s;break}}if(!key)continue;const hk=norm(hd);if(out.some(o=>norm(o.t)===hk))continue;out.push({t:hd.replace(/^\d+[.)-]?\s*/,''),k:key})}
 if(out.length<4&&course?.sections?.length){const facts=(window.PULSE_V12_FACTS_FOR?.(title)?.facts||[]).map(sentence).filter(usable);course.sections.forEach((s,i)=>{if(out.length<10&&!out.some(o=>norm(o.t)===norm(s)))out.push({t:s,k:facts[i]||facts[0]||'Partie importante du support à connaître.'})})}
 if(!out.length){const facts=(window.PULSE_V12_FACTS_FOR?.(title)?.facts||[]).map(sentence).filter(usable).slice(0,6);facts.forEach((f,i)=>out.push({t:'Point clé '+(i+1),k:f}))}
 return out.slice(0,10)
}
function outlineHTML(title,compact=false){const rows=outline(title);if(!rows.length)return'';return `<details class="v19outline ${compact?'compact':''}" open><summary><span><b>Plan du cours</b><small>${rows.length} parties • une idée clé par partie</small></span><em>⌄</em></summary><div class="v19outlineBody">${rows.map((r,i)=>`<details class="v19part" ${i===0&&!compact?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><b>${h(r.t)}</b><em>+</em></summary><p>${h(r.k)}</p></details>`).join('')}</div></details>`}
function injectOutlines(){document.querySelectorAll('.v15summary').forEach(s=>{if(s.querySelector('.v19outline'))return;const title=s.querySelector('.v15sumHead p')?.textContent?.trim();if(!title)return;const src=s.querySelector('.v15source');(src||s).insertAdjacentHTML(src?'beforebegin':'beforeend',outlineHTML(title,false))})}
function qcmTitle(){return document.querySelector('.seriesBar b')?.textContent?.replace(/^Plan\s*•\s*/i,'').trim()||''}
function injectQcmOutline(){const q=document.querySelector('.rpPlanQuestion');if(!q||q.querySelector('.v19qOutline'))return;const title=qcmTitle();if(!title)return;const box=document.createElement('div');box.className='v19qOutline';box.innerHTML=outlineHTML(title,true);const feedback=q.querySelector('.feedback');if(feedback)q.insertBefore(box,feedback);else q.appendChild(box)}
function addSummaryToggle(){const course=document.querySelector('.courseDetail .v15course');if(!course||course.querySelector('.v19sumToggle'))return;const summary=course.querySelector('.v15summary');if(!summary)return;const b=document.createElement('button');b.type='button';b.className='v19sumToggle';b.textContent='Masquer la synthèse';b.onclick=()=>{const hidden=course.classList.toggle('v19summaryHidden');b.textContent=hidden?'Afficher la synthèse':'Masquer la synthèse';setTimeout(()=>window.dispatchEvent(new Event('resize')),80)};course.prepend(b)}
function fixSelectNone(){const b=document.getElementById('rpSelectNone');if(!b||b.dataset.v19fixed)return;b.dataset.v19fixed='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const checked=[...document.querySelectorAll('[data-rp-menu-q]:checked,[data-rp-menu-course]:checked')];checked.forEach(x=>x.click());setTimeout(()=>{document.querySelectorAll('[data-rp-menu-q],[data-rp-menu-course]').forEach(x=>x.checked=false);const launch=document.getElementById('rpLaunch');if(launch)launch.disabled=true;const span=document.querySelector('.rpMenuActions span');if(span)span.textContent='0 QCM sélectionné(s)'},20)},true)}
function addViewerFullLabel(){document.querySelectorAll('.courseDetail .v17viewer').forEach(v=>{if(v.querySelector('.v19fullCourse'))return;const tb=v.querySelector('.v17toolbar');if(!tb)return;const b=document.createElement('button');b.className='v19fullCourse';b.type='button';b.textContent='⛶ Cours plein écran';b.onclick=()=>v.requestFullscreen?.();tb.appendChild(b)})}
let timer;function tick(){clearTimeout(timer);timer=setTimeout(()=>{injectOutlines();injectQcmOutline();addSummaryToggle();fixSelectNone();addViewerFullLabel()},70)}new MutationObserver(tick).observe(document.documentElement,{subtree:true,childList:true});setTimeout(tick,200);
window.PULSE_OUTLINE_V19={outline};
})();