(()=>{
const labels={home:['⌂','Accueil','Vue d’ensemble'],courses:['▤','Cours UNESS','Supports & synthèses'],train:['✦','QCM & entraînement','Séries personnalisées'],plan:['◈','Plan adaptatif','Cours + QCM / jour'],reviews:['↻','Révisions','Répétition espacée'],stats:['▥','Performance','Progression & scores'],account:['◎','Compte','Cloud & appareils']};
function buttonHTML(k){const [i,t,s]=labels[k];return `<span class="v21NavIcon">${i}</span><span class="v21NavText"><b>${t}</b><small>${s}</small></span>`}
function ensureSidebar(){const box=document.querySelector('.sidebar .nav');if(!box)return;let p=box.querySelector('button[data-view="plan"]');if(!p){p=document.createElement('button');p.dataset.view='plan';const reviews=box.querySelector('button[data-view="reviews"]');reviews?box.insertBefore(p,reviews):box.appendChild(p)}
 Object.keys(labels).forEach(k=>{const b=box.querySelector(`button[data-view="${k}"]`);if(!b)return;const count=k==='reviews'?b.querySelector('.count')?.textContent:null;b.innerHTML=buttonHTML(k)+(count?`<span class="count">${count}</span>`:'');b.classList.toggle('active',view===k);b.onclick=()=>{view=k;render()}});
 box.querySelectorAll('.v22NavLabel').forEach(x=>x.remove());[['home','PILOTAGE'],['courses','APPRENDRE'],['plan','PLANIFIER'],['reviews','SUIVRE']].forEach(([k,t])=>{const b=box.querySelector(`button[data-view="${k}"]`);if(!b)return;const d=document.createElement('div');d.className='v21NavLabel v22NavLabel';d.textContent=t;box.insertBefore(d,b)});document.querySelector('.sidebar')?.classList.add('v21Sidebar')}
function ensureMobile(){const box=document.querySelector('.mobilebar');if(!box)return;let p=box.querySelector('button[data-view="plan"]');if(!p){p=document.createElement('button');p.dataset.view='plan';p.innerHTML='◈<br>Plan';const r=box.querySelector('button[data-view="reviews"]');r?box.insertBefore(p,r):box.appendChild(p)}box.querySelectorAll('button[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.onclick=()=>{view=b.dataset.view;render()}})}
let timer;function run(){clearTimeout(timer);timer=setTimeout(()=>{ensureSidebar();ensureMobile()},35)}
window.PULSE_PREMIUM_NAV=()=>{ensureSidebar();ensureMobile()};new MutationObserver(run).observe(document.documentElement,{subtree:true,childList:true});setTimeout(run,120);
})();