(()=>{
const labels={home:['⌂','Accueil','Vue d’ensemble'],courses:['▤','Cours UNESS','Supports & synthèses'],train:['✦','QCM & entraînement','Séries personnalisées'],plan:['◈','Plan adaptatif','Cours + QCM / jour'],reviews:['↻','Révisions','Répétition espacée'],stats:['▥','Performance','Progression & scores'],account:['◎','Compte','Cloud & appareils']};
function buttonHTML(k,count=''){const [i,t,s]=labels[k];return `<span class="v21NavIcon">${i}</span><span class="v21NavText"><b>${t}</b><small>${s}</small></span>${k==='reviews'&&count?`<span class="count">${count}</span>`:''}`}
function enhanceButton(box,k){let b=box.querySelector(`button[data-view="${k}"]`);if(!b&&k==='plan'){b=document.createElement('button');b.dataset.view='plan';const reviews=box.querySelector('button[data-view="reviews"]');reviews?box.insertBefore(b,reviews):box.appendChild(b)}if(!b)return;const count=k==='reviews'?b.querySelector('.count')?.textContent||'':'';if(b.dataset.p22Enhanced!=='1'){b.innerHTML=buttonHTML(k,count);b.dataset.p22Enhanced='1'}b.classList.toggle('active',view===k)}
function ensureLabels(box){const defs=[['home','PILOTAGE'],['courses','APPRENDRE'],['plan','PLANIFIER'],['reviews','SUIVRE']];for(const [k,t] of defs){const b=box.querySelector(`button[data-view="${k}"]`);if(!b)continue;let d=b.previousElementSibling;if(!(d&&d.classList.contains('v22NavLabel')&&d.dataset.for===k)){d=document.createElement('div');d.className='v21NavLabel v22NavLabel';d.dataset.for=k;d.textContent=t;box.insertBefore(d,b)}}}
function ensureSidebar(){const box=document.querySelector('.sidebar .nav');if(!box)return;Object.keys(labels).forEach(k=>enhanceButton(box,k));ensureLabels(box);document.querySelector('.sidebar')?.classList.add('v21Sidebar')}
function ensureMobile(){const box=document.querySelector('.mobilebar');if(!box)return;let p=box.querySelector('button[data-view="plan"]');if(!p){p=document.createElement('button');p.dataset.view='plan';p.innerHTML='◈<br>Plan';const r=box.querySelector('button[data-view="reviews"]');r?box.insertBefore(p,r):box.appendChild(p)}box.querySelectorAll('button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function ensure(){ensureSidebar();ensureMobile()}
if(!window.__pulseNavDelegated){window.__pulseNavDelegated=true;document.addEventListener('click',e=>{const b=e.target.closest?.('.sidebar button[data-view],.mobilebar button[data-view]');if(!b)return;e.preventDefault();const next=b.dataset.view;if(!next||next===view)return;view=next;selectedCourse=null;render()},{capture:true})}
let raf=0;const root=document.getElementById('root')||document.body;new MutationObserver(ms=>{if(!ms.some(m=>m.type==='childList'&&m.target===root))return;cancelAnimationFrame(raf);raf=requestAnimationFrame(ensure)}).observe(root,{childList:true});
window.PULSE_PREMIUM_NAV=ensure;requestAnimationFrame(ensure);
})();